### ISSUE TITLE
I can't see the command i am typing

### ISSUE THREAD

**Issue by khansaad1275** [MrAlpha786/termux-backup-restore#10]
When using this tool after either backup or restore I am unable to see commands i am typing, like it goes in Password mode ( it's there but we can't see it ) to fix that you need to restart termux. Please solve this issue, Other than that, This tool is Awesome <3

**Comment by ghost** [comment]
Why would you type while backing up? But nevertheless you could create a new termux session or cancel it (`Ctrl-C`)

**Comment by MrAlpha786** [comment]
Hey @khansaad1275 

Thanks for letting me know. I have fixed the issue now.

But I advice you to start a new session after restoring backup.
