### ISSUE TITLE
termux-setup-storage running everytime the script runs; backup "files" directory.

### ISSUE THREAD

**Issue by ghost** [MrAlpha786/termux-backup-restore#2]
### Request
Hi, I would like to run termux-setup-storage **if** the user has not run it yet.
I also would like to backup the "files" directory in order to backup directories and files created by the user.
### Problem
I did edit the [files](https://github.com/GrpeApple/TERBR-TermuxBackupTool/tree/termux-backup-restore-GrpeApple-1), but I don't know the version naming scheme.
### What to do
Edit CHANGELOG.md, Change Version Number ( Below the comment and delete the comment also. )
Create pull request.
### Files changed
* CHANGELOG.md
* terbr

**Comment by MrAlpha786** [comment]
Hi, I have seen your changes and have some suggestions.

for termux-setup-storage it is better to not depend on $HOME/storage directory.

Instead we can check if the /storage/emulated/0/ is writable or not.

Also, I'm working on terbr v4, you can check the v4 branch

**Comment by ghost** [comment]
~Wouldn't it be better if the directory was /sdcard?~
Going to check out the branch.
~Looking forward to support zsh and autocompletion. ( However for later support because maybe we are not prepared yet? )~

Thanks. ~for the backup~

**Comment by MrAlpha786** [comment]
Should I close this issue?

**Comment by ghost** [comment]
Yes, I was supposed to ask that the user needs to choose what to backup. Can close this issue.

**Comment by MrAlpha786** [comment]
Will proprably add this feature😁

**Comment by ghost** [comment]
Probably won't add all features in a single issue, will fix my habit.
