### ISSUE TITLE
Prevent Screen from sleeping

### ISSUE THREAD

**Issue by ghost** [MrAlpha786/termux-backup-restore#3]
Using termux-wake-lock, it prevents the CPU from sleeping. Although I don't know if it is from Termux:API.
Using termux-wake-unlock, it exits wakelock.

You can check my branch (v4).
What do you suggest?

**Comment by MrAlpha786** [comment]
Its not from termux api. We can use it -- as without pigz installed,  backup takes more than a minute (depends on size).

**Comment by ghost** [comment]
Gonna work on it. ( Night time here so maybe tomorrow. )
