### ISSUE TITLE
Meta - Add CONTRIBUTING.md and also Add Releases?

### ISSUE THREAD

**Issue by ghost** [MrAlpha786/termux-backup-restore#5]
# Add CONTRIBUTING.MD
## Sidenote
Sorry, if I just created a lot of work.
But, this could be added later.
## Problem
How can users contribute?
What formatting and syntax will they follow?
etc....
## Opinion
Create CONTRIBUTING.md and add etc....

**Comment by ghost** [comment]
# Add Releases
## Sidenote
Sorry my habit.
## Problem
I see that there is version numbers. Like v3.0 or something.
## Opinion
Thought that adding releases or tags might benefit.

**Comment by MrAlpha786** [comment]
As this is such a small script. I am not expecting any contributions. 
 But as you asked I am using POSIX syntax. With tabwidth of 2.

About Releases, I'm lazy

**Comment by ghost** [comment]
Ok 👍🏼
