### ISSUE TITLE
Missing tab?

### ISSUE THREAD

**Issue by ghost** [MrAlpha786/termux-backup-restore#6]
At
```

while getopts ':hvVbr:' arg; do
	case $arg in
		b) unset TERBR_RESTORE; TERBR_BACKUP=True
            ;;

        r) unset TERBR_BACKUP; TERBR_RESTORE=True; TERBR_RESTORE_FILE=${OPTARG};
            ;;

		V) TERBR_VERBOSE=True
            ;;

```
where 
> `r) unset TERBR_BACKUP; TERBR_RESTORE=True; TERBR_RESTORE_FILE=${OPTARG}; `
is missing a tab on the rest of the case.

And also there are lots of spaces and tabs, is it necessary to correct them?

**Comment by MrAlpha786** [comment]
that was happening because of my vim settings. I have fixed it now.

Plus I have changed the tabwidth to 2 spaces.

**Comment by ghost** [comment]
Thanks, vim is awesome.
