### ISSUE TITLE
7z Support

### ISSUE THREAD

**Issue by ghost** [MrAlpha786/termux-backup-restore#7]
If for example that the size is too large, it defaults to 7z in order to make it smaller.
But use with tar because 7z does not store owner/group.
### Example
```
cd /data/data
tar -cf - com.termux | 7z a -si -mx=9 /storage/emulated/0/Download/com.termux.7z
```
But there are too many ultra options, maybe in the future.

**Comment by MrAlpha786** [comment]
I think there's no need for this.

**Comment by ghost** [comment]
Cool.
