### ISSUE TITLE
Error when directory has a space when restoring

### ISSUE THREAD

**Issue by ghost** [MrAlpha786/termux-backup-restore#8]
When passing argument `/storage/emulated/0/Any\ Directory\ with\ spaces/backup_file.bak` to `terbr -r` or anything with restore option,

makes ${OPTARG} parses it as `/storage/emulated/0/Any Directory with spaces/backup_file.bak` causing an error:

```
/data/data/com.termux/files/usr/bin/terbr: line 147: [: /storage/emulated/0/Any: binary operator expected
Restoring from '/storage/emulated/0/Any Directory with spaces/backup_file.bak'

[*] Restoring Files...............
[It may take a while. Please wait...

tar: /storage/emulated/0/Any: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```
(Also if a directory other than `Any Directory with spaces`   like   `Any`, that doesn't solve the problem.)

I am currently working on it, but I may need some assistance.

**Comment by MrAlpha786** [comment]
quoting TERBR_BACKUP_FILE and TERBR_RESTORE_FILE will solve the problem

**Comment by MrAlpha786** [comment]
I have fixed the bug.
check [commit](https://github.com/MrAlpha786/TERBR-TermuxBackupTool/commit/bdf73f170fa05e23ac0f56291c6b3a197c459bc8)
