### ISSUE TITLE
Add install and uninstall scripts and configure terbr

### ISSUE THREAD

**Issue by ghost** [MrAlpha786/termux-backup-restore#9]
Sorry for me being late, I created install.sh and uninstall.sh and edited README.md to show documentation to install and uninstall terbr, I have also added option to allow Custom PREFIX. Feel free to remove or suggest something, but here is the problem. I need help setting things up in configure.sh. Sorry for committing changes without your consent for adding a feature.

I am quite busy.

**Comment by ghost** [comment]
It seems it has been merged.
MrAlpha786/TERBR-TermuxBackupTool@93f0546b24dbd3bb13ce3a0468f3c56dced97168

**Comment by MrAlpha786** [comment]
Main motive is to keep it simple. Dropped some feature like file manager and PREFIX backup for simplicity.

Will probably add them back if there's a simple way to implement.

But the idea is one simple script.
